### ISSUE TITLE
Missing git tag for 6.4

### ISSUE THREAD

**Issue by kloczek** [hrw/python-syscalls#5]
According to https://pypi.org/project/system-calls/ latest version is 6.4 however here there is no corresponding git tag for that version.
Not pushed local git repo to github? 🤔

**Comment by hrw** [comment]
Thanks for noticing. Pushed 5.19.0 and 6.4.0 tags (no code changes).

I wonder is there anyone using it ;D

**Comment by kloczek** [comment]
Thank you 👍 😄 
If I can choose between sdist or autogenerated from git tag tar ball I'm always choosing tagged resources because it guarantees that I would be able to apply patches downloaded from git commits 😋 
IIRC Arch linux ATM has kind of similar policy.
